namespace _Game.Scripts
{
	public enum GameEvents
	{
		None,
		PlayTime,
		Timer,
		Timer24,
		VideoAdError,
		VideoAdStarted,
		VideoAdShowed,
		Rate_us,
		RewardVideoAdShowed,
		InterstitialVideoAdShowed,
		RewardVideoAdError,
		InterstitialVideoAdError,
		InterstitialVideoAdStarted,
		RewardVideoAdStarted,
		RewardVideoAvailable,
		LevelStart,
		LevelComplete,
		LevelFail,
		FirstSession,
		GameStart,
		InAppPurchased,
		BannerStart,
		CloseReward,
	}
}